[build]
  command = "npm run build"
  publish = "dist"
  node_version = "20"


[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
